version: '3.3'
services:

  prometheus:
    image: prom/prometheus:v2.7.2
    container_name: 'prometheus'
    network_mode: bridge
    ports:
      - '9090:9090'
    volumes:
      - ./metrics/adapter/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway:v0.6.0
    container_name: 'pushgateway'
    network_mode: bridge
    ports:
      - '9091:9091'

  grafana:
    image: grafana/grafana:6.0.2
    container_name: 'grafana'
    network_mode: bridge
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/home/ivan/workspace/grafana

  mongo:
    image: mongo
    container_name: mongo
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27018:27017"
    volumes:
      - /home/ivan/workspace/volumes/mongo:/data/db
    network_mode: bridge

  postgres:
    image: postgres
    container_name: postgres
    network_mode: bridge
    volumes:
      - ./gateway/adapter/src/main/resources/spring-data.sql:/docker-entrypoint-initdb.d/db.sql
      - /home/ivan/workspace/volumes/postgresql:/private/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: dadosabertos