on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: build
        run: docs/script/bootstrap
      - name: test
        run: docs/script/cibuild